/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    
    public String getGreeting() {
        return "Observer Pattern.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Channel rockChannel = new Channel("Rock channel");
        Channel javaChannel = new Channel("Java channel");

        Follower follower1 = new Follower("Foll 1");
        Follower follower2 = new Follower("Foll 2");
        Follower follower3 = new Follower("Foll 3");
        Follower follower4 = new Follower("Foll 4");
        Follower follower5 = new Follower("Foll 5");

        rockChannel.registerObserver(follower1);
        rockChannel.registerObserver(follower2);
        rockChannel.registerObserver(follower3);
        javaChannel.registerObserver(follower4);
        javaChannel.registerObserver(follower5);

        rockChannel.setStatus("on live today");
        javaChannel.setStatus("Deing Pattern fore ever");

    }
}
