/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "**********The Adapter Pattern**********\n";
    }

    public static void main(String[] args) {
        //create objects
        CoffeeMachineInterface coffeMachine =
            new CoffeeTouchscreenAdapter(new OldCoffeeMachine());
        CoffeMachineClient client = new CoffeMachineClient(coffeMachine);

        //run program
        client.makeCoffe(CoffeMachineClient.Flavor.A);
        client.makeCoffe(CoffeMachineClient.Flavor.B);
        client.makeCoffe(null);
    }
}
